# Generated by Django 4.0.6 on 2022-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0007_alter_aktor_filmy_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (0, 'Inne'), (4, 'Drama'), (1, 'Horror')], default=0),
        ),
    ]
