# Generated by Django 4.0.6 on 2022-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0009_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (4, 'Drama'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia')], default=0),
        ),
    ]
