# Generated by Django 4.0.6 on 2022-10-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0010_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dodatkoweinfo',
            name='gatunek',
        ),
        migrations.AddField(
            model_name='dodatkoweinfo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nowe'), (1, 'Otwarte'), (2, 'Rozwiązane'), (3, 'Wstrzymane')], default=0),
        ),
    ]
